name: TruffleRuby Dev Builds
on:
  workflow_dispatch:
  push:
    tags:
    - '*'
  schedule:
  - cron: '0 8 * * *'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm, macos-13, macos-14 ]
        name: [ '-head', '+graalvm-head', '+graalvm-ea' ]
    continue-on-error: ${{ matrix.name == '+graalvm-ea' }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone truffleruby
      uses: actions/checkout@v4
      with:
        repository: andrykonchin/truffleruby
        ref: ak/update-joni-checksum
    - uses: actions/checkout@v4
      with:
        path: truffleruby-dev-builder
      if: matrix.name == '+graalvm-ea'

    - name: Set platform
      id: platform
      run: |
        platform=${{ matrix.os }}
        platform=${platform/macos-13/macos-latest}
        platform=${platform/macos-14/macos-13-arm64}
        platform=${platform/%-arm/-arm64}
        echo "platform=$platform" >> $GITHUB_OUTPUT

    # Build
    - name: Setup system ruby
      uses: ruby/setup-ruby@master
      with:
        ruby-version: 3.2
    - name: Setup system python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
      if: startsWith(matrix.os, 'macos')
    - run: sudo apt-get install -y --no-install-recommends libyaml-dev
      if: startsWith(matrix.os, 'ubuntu')

    - name: Setup jt
      run: echo "$PWD/bin" >> $GITHUB_PATH
    - name: Clone Graal
      run: jt sforceimports
    - name: Install JVMCI
      run: |
        jt install jvmci
        echo "JAVA_HOME=$(jt install jvmci)" >> $GITHUB_ENV
    - name: Install mx
      run: jt mx --version

    - run: free -m
      if: startsWith(matrix.os, 'ubuntu')
    - name: Build TruffleRuby (native)
      run: jt build --env native --extra-image-builder-argument=rubyvm:-J-XX:MaxRAMPercentage=100
      if: matrix.name == '-head'
    - name: Build TruffleRuby (jvm)
      run: jt build --env jvm-ce-libgraal
      if: matrix.name == '+graalvm-head'
    - name: Build TruffleRuby (jvm-ea)
      run: ruby truffleruby-dev-builder/ea-build-with-truffleruby-master.rb
      if: matrix.name == '+graalvm-ea'

    - run: mkdir -p ~/.rubies
    - run: mv $(jt mx --env native standalone-home --type=native ruby) ~/.rubies/truffleruby${{ matrix.name }}
      if: matrix.name == '-head'
    - run: mv $(jt mx --env jvm-ce-libgraal standalone-home --type=jvm ruby) ~/.rubies/truffleruby${{ matrix.name }}
      if: matrix.name == '+graalvm-head'
    - run: mv truffleruby-jvm-ea-master-build ~/.rubies/truffleruby${{ matrix.name }}
      if: matrix.name == '+graalvm-ea'
    - name: Create archive
      run: tar czf truffleruby${{ matrix.name }}-${{ steps.platform.outputs.platform }}.tar.gz -C ~/.rubies truffleruby${{ matrix.name }}

    - name: Basic test
      run: ~/.rubies/truffleruby${{ matrix.name }}/bin/ruby --version
    - name: OpenSSL test
      run: ~/.rubies/truffleruby${{ matrix.name }}/bin/ruby -ropen-uri -e 'puts URI.send(:open, %{https://rubygems.org/}) { |f| f.read(1024) }'

